machine:
  decoder:
    namespace: arm
  extras:
    arch_type: arm
instructions:
  - name: arm_add_imm_a1
    format: xxxx:cond|00|1|0100|x:S|xxxx:Rn|xxxx:Rd|xxxx xxxx xxxx:imm12
    condition:
      cond: '!= 15'
    extras:
      clocks: 10
  - name: push_1
    format: xxxx:cond|1001 00|1|0|1101|xxxx xxxx xxxx xxxx:register_list
    condition:
      cond: in_range 0-14
  - name: arm_mov_imm_a1
    format: xxxx:cond|00|1|1101|x:S|0000|xxxx:Rd|xxxxxxxxxxxx:imm12
    extras:
      clocks: 10
  - name: arm_mov_imm_a2
    format: xxxx:cond|0011|0000|xxxx:imm4|xxxx:Rd|xxxxxxxxxxxx:imm12
    extras:
      clocks: 10
